model:
  checkpoint: ~
  params:
    in_size: [10, 100, 100]
    channels: 1
    out_conv_blocks: 1
    model_channels: 16
    num_res_blocks: [1, 1]
    attention_resolutions: [4, 8]
    dropout: 0.0
    gen_channel_mult: [1, 2, 2, 4]
    disc_channel_mult: [4, 4, 8]
    out_mult: 1
    gen_z_down: [2, 4, 8]
    disc_z_down: []
    conv_resample: True
    num_heads: 8
    activation: silu

setting:
  epoch: 30
  batch_size: 4
  num_workers: 6
  pin_memory: True
  log_every: 100
  max_save: 30
  max_iters: 1600

criterion:
  lr: 1.0e-4
  weight_decay: 5.0e-3
  clip_grad: 5.0
  pos_weight: [0.1, 1.0, 2.0] # None O H
  cond_weight: 1.0
  xy_weight: 0.5
  z_weight: 0.5

  schedular:
    name: StepLR
    params:
      step_size: 10
      gamma: 0.1

dataset:
  source_path: datafiles/20240923-bulk-Hup-train/afm
  source_cutinfo: ""
  target_path: datafiles/20240923-crop-afm
  target_cutinfo: datafiles/exp/all-info.csv

  num_images: [4, 3, 3]
  image_size: [100, 100]
  image_split: [8, 16]
  real_size: [25.0, 25.0, 3.0]
  ion_type: ['O', 'H']
  split: [0.0, 3.0]
  nms: True